pod: ${POD_NAME:unknown}
server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:testdb};DB_CLOSE_DELAY=-1
    username: ${DB_USER:test}
    password: ${DB_PASSWORD:test}
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    prometheus:
        enabled: true
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true